# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "usr", color = "(RD)"}
hostname  = {icon = " ", name = "hname", color = "(YW)"}
distro    = {icon = "󰌽 ", name = "os", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
uptime    = {icon = " ", name = "upt", color = "(BE)"}
desktop   = {icon = "󱂬 ", name = "wm", color = "(CN)"}
# packages  = {icon = " ", name = "pkgs", color = "(RD)"}  # WARNING: Resource Intensive
terminal  = {icon = " ", name = "term", color = "(RD)"}
shell     = {icon = " ", name = "shell", color = "(MA)"}
# weather   = {icon = " ", name = "weather", color = "(BE)"} # Requires curl and an emoji font. | WARNING: Resource Intensive
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}      # WARNING: Resource Intensive
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# battery   = {icon = " ", name = "bat", color = "(GN)"}
# memory    = {icon = " ", name = "mem", color = "(YW)"}
# The following stats do not work on MacOS and the BSDs.
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = " "}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0.5
location = "" # Used for fetching weather; leave empty to use the location of your IP; check https://wttr.in/:help for supported location types

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "" # Please only use absolute paths.
scale  = 28
margin = [1, 2, 3]

