[globals]
animation_duration = 1.0
show_duration = 5.0
text-color = "#000"
background = "#fff"
foreground_color = "#fff"

[actions.LeftClick]
action = "OpenNotification"

[actions.RightClick]
action = "Close"

[actions.ScrollUp]
action = "Close"

[window]
position = "Top"
radius = 100
width = 600
height = 80

[battery]
enabled = false
refresh_time = 30.0

[battery.level.15]
icon = "󰁺"
show_duration = 10.0
background = "#ff6961"
foreground = "#fff"

[battery.level.30]
icon = "󰁼"
show_duration = 5.0
background = "#000"
foreground = "#fff"

[urgency.low]
show_duration = 5.0
background = "#000"
foreground_color = "#fff"

[urgency.normal]
show_duration = 5.0
background = "#000"
foreground_color = "#fff"

[urgency.critical]
show_duration = 10.0
background = "#ff6961"
foreground_color = "#fff"
