"$schema" = 'https://starship.rs/config-schema.json'

palette = "neifua"

[character]
success_symbol = "[[;neifua](#6F9D88) ❯](#c4cbc1)"
error_symbol = "[[;neifua](#6d203d) ❯](#c4cbc1)"
vimcmd_symbol = "[;neifua ❮](subtext1)"

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

[palettes.neifua]
background = "#0c0d0c"
text = "#c4cbc1"
subtext1 = "#898e87"
subtext0 = "#7D7870"
overlay2 = "#8D9C70"
overlay1 = "#6B8A6D"
overlay0 = "#72853C"
surface2 = "#6F9D88"
surface1 = "#526E5D"
surface0 = "#7D7870"
base = "#0c0d0c"
mantle = "#1a1b1a"
crust = "#131513"
rosewater = "#8D9C70"
flamingo = "#72853C"
pink = "#9c708d"
mauve = "#7D708C"
red = "#8c4e4e"
maroon = "#7c3f3f"
peach = "#a0723c"
yellow = "#c4cbc1"
green = "#6B8A6D"
teal = "#6F9D88"
sky = "#6CA6A6"
sapphire = "#5CA5A5"
blue = "#5D7EA0"
lavender = "#9DAAC4"